/**
 * AUTO-GENERATED by scripts/private-encrypt.mjs — do not edit by hand.
 * Source of truth: private/*.md + private/grants.json (both gitignored).
 * This file is PUBLIC ciphertext: no plaintext and no passwords live here.
 * Run: npm run private
 */
export const privateConfig = {
  "salt": "lapvsyR6gOrBrY8sR8PGKQ==",
  "iterations": 600000
};

export const privatePosts = [
  {
    slug: "p-36ffeb0b59",
    title: "private_test",
    tags: ["私密"],
    date: "2026-08-27",
    excerpt: "TEST...",
    lead: "",
    wordCount: 1,
    readingMinutes: 1,
    keys: [{"grant":"admin","iv":"jegz+irUoRWoKGg/","data":"+fqnE6qw90loWvQBOK6kdZVA3X1khlvybOgmf1F2Uv2xlbsn+HWVcAJE29rCC4uW"},{"grant":"guest-001","iv":"9jlrHD0RU7nhVJGk","data":"9ry8+Cc7TQ462pQHDcwhStGss4+4d7xknGi41Y/t0v29lcdf7ZC0qVl+LF2dX/mH"}],
    cipher: {"iv":"aeQYmbU9NVwKzZDj","data":"1fQ6LDtPl1Fqi5frnNB0KGUz6M4uRcPgu11gBs8pPYRb8Wg9+0KvYssKaPHMSbKD+QdI5OJskOmsLYIUpvtQU0B/3YWsLLsG"},
  }
];
