/**
 * AUTO-GENERATED by scripts/private-encrypt.mjs — do not edit by hand.
 * Source of truth: private/*.md + private/grants.json (both gitignored).
 * This file is PUBLIC ciphertext: no plaintext and no passwords live here.
 * Run: npm run private
 */
export const privateConfig = {
  "salt": "uaag5TnxEBSYpb/dVh4mUA==",
  "iterations": 600000
};

export const privatePosts = [
  {
    slug: "p-36ffeb0b59",
    title: "private_test",
    tags: ["私密"],
    date: "2026-08-27",
    excerpt: "TEST...",
    lead: "",
    wordCount: 1,
    readingMinutes: 1,
    keys: [{"grant":"admin","iv":"YdZZ8tQC3KPjo/nc","data":"CZw16dSISeho6T85NQ8TigJ0FCO1M6zxcwxq3uHQqwhj4bQJUdHP4E9gGP8wpkKI"},{"grant":"guest-001","iv":"IKD6zoPXNIL3x+eW","data":"4vIqWqIpV25p0Oyfv74poX3p2BT4NkyG7A6gqSUQ8qHOqPFm7TuTz9GTBF8YAVhH"}],
    cipher: {"iv":"DHPMs6NGkCAH8VRt","data":"N9PR6SiQMqc/xZFJ2WPSiukXifu2jHhNDCB3goTJCSgm9Rbu8EkBf74qjpeiSoxkeoNmycTvGMjHuG13zsfS/JpNGCAtqItw"},
  }
];
