/**
 * AUTO-GENERATED by scripts/private-encrypt.mjs — do not edit by hand.
 * Source of truth: private/*.md + private/grants.json (both gitignored).
 * This file is PUBLIC ciphertext: no plaintext and no passwords live here.
 * Run: npm run private
 */
export const privateConfig = {
  "salt": "xMmQ3Yvmh7O2dSX0qzboUg==",
  "iterations": 600000
};

export const privatePosts = [

];
